[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.1"
  export = ["dsg"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "dsg"
  org = "mirajabeysekara"
  version = "1.0.0"

